/* 
   ========================================================================
   PSX Retro Mesh: automag_lvl1
   Generated by: PSX Retro Mesh Generator
   Compatible with: Raylib 4.0+ and OmegaTech C Engines
   ========================================================================
*/

#ifndef RETRO_MESH_AUTOMAG_LVL1_H
#define RETRO_MESH_AUTOMAG_LVL1_H

#include "raylib.h"
#include <stdlib.h>

// Mesh properties
#define AUTOMAG_LVL1_VERTEX_COUNT 31
#define AUTOMAG_LVL1_TRIANGLE_COUNT 44

// Static vertex positions (x, y, z)
static const float automag_lvl1_vertices[] = {
    -0.1500f, 0.4000f, 1.4000f,     -0.1500f, 0.4000f, -1.2000f,
    -0.1500f, 0.1000f, -1.2000f,     -0.1500f, 0.1000f, -0.3000f,
    -0.1500f, 0.1000f, 1.4000f,     -0.1500f, -0.9000f, -0.8000f,
    -0.1500f, -0.9000f, -1.1000f,     -0.1500f, -0.1000f, -1.3000f,
    -0.1500f, -0.3000f, -0.3000f,     0.1500f, 0.4000f, 1.4000f,
    0.1500f, 0.4000f, -1.2000f,     0.1500f, 0.1000f, -1.2000f,
    0.1500f, 0.1000f, -0.3000f,     0.1500f, 0.1000f, 1.4000f,
    0.1500f, -0.9000f, -0.8000f,     0.1500f, -0.9000f, -1.1000f,
    0.1500f, -0.1000f, -1.3000f,     0.1500f, -0.3000f, -0.3000f,
    0.0000f, 0.5200f, 1.2000f,     -0.0500f, 0.4000f, 1.3000f,
    0.0500f, 0.4000f, 1.3000f,     -0.0500f, 0.4000f, 1.1000f,
    0.0500f, 0.4000f, 1.1000f,     -0.0600f, 0.4800f, -0.9000f,
    0.0600f, 0.4800f, -0.9000f,     -0.0600f, 0.4800f, -1.1000f,
    0.0600f, 0.4800f, -1.1000f,     -0.0600f, 0.4000f, -0.9000f,
    0.0600f, 0.4000f, -0.9000f,     -0.0600f, 0.4000f, -1.1000f,
    0.0600f, 0.4000f, -1.1000f, 
};

// Aligned texture coordinates (u, v) - mapped flat per face corner
static const float automag_lvl1_texcoords[] = {
    0.4000f, 0.1000f,
    0.1000f, 0.3000f,
    0.4000f, 0.3000f,
    0.4000f, 0.1000f,
    0.0000f, 0.1000f,
    0.1000f, 0.3000f,
    0.0000f, 0.1000f,
    0.0000f, 0.3000f,
    0.1000f, 0.3000f,
    0.0000f, 0.5000f,
    0.2000f, 0.7000f,
    0.2000f, 0.5000f,
    0.0000f, 0.5000f,
    0.0000f, 0.7000f,
    0.2000f, 0.7000f,
    0.0000f, 0.7000f,
    0.1000f, 0.9000f,
    0.2000f, 0.7000f,
    0.2000f, 0.7000f,
    0.1000f, 0.9000f,
    0.3000f, 0.9000f,
    0.9000f, 0.1000f,
    0.9000f, 0.3000f,
    0.6000f, 0.3000f,
    0.9000f, 0.1000f,
    0.6000f, 0.3000f,
    0.5000f, 0.1000f,
    0.5000f, 0.1000f,
    0.6000f, 0.3000f,
    0.5000f, 0.3000f,
    0.5000f, 0.5000f,
    0.7000f, 0.7000f,
    0.7000f, 0.5000f,
    0.5000f, 0.5000f,
    0.5000f, 0.7000f,
    0.7000f, 0.7000f,
    0.5000f, 0.7000f,
    0.6000f, 0.9000f,
    0.7000f, 0.7000f,
    0.7000f, 0.7000f,
    0.6000f, 0.9000f,
    0.8000f, 0.9000f,
    0.8000f, 0.1000f,
    0.9000f, 0.1000f,
    0.9000f, 0.2000f,
    0.8000f, 0.1000f,
    0.9000f, 0.2000f,
    0.8000f, 0.2000f,
    0.8000f, 0.2000f,
    0.8000f, 0.3000f,
    0.9000f, 0.3000f,
    0.8000f, 0.2000f,
    0.9000f, 0.3000f,
    0.9000f, 0.2000f,
    0.8000f, 0.3000f,
    0.8000f, 0.4000f,
    0.9000f, 0.4000f,
    0.9000f, 0.3000f,
    0.9000f, 0.4000f,
    0.8000f, 0.3000f,
    0.8000f, 0.5000f,
    0.9000f, 0.5000f,
    0.9000f, 0.6000f,
    0.8000f, 0.5000f,
    0.9000f, 0.6000f,
    0.8000f, 0.6000f,
    0.8000f, 0.6000f,
    0.8000f, 0.7000f,
    0.9000f, 0.7000f,
    0.8000f, 0.6000f,
    0.9000f, 0.7000f,
    0.9000f, 0.6000f,
    0.8000f, 0.7000f,
    0.9000f, 0.7000f,
    0.9000f, 0.8000f,
    0.8000f, 0.7000f,
    0.9000f, 0.8000f,
    0.8000f, 0.8000f,
    0.8000f, 0.8000f,
    0.9000f, 0.8000f,
    0.9000f, 0.9000f,
    0.8000f, 0.8000f,
    0.9000f, 0.9000f,
    0.8000f, 0.9000f,
    0.8000f, 0.9000f,
    0.9000f, 0.9000f,
    0.9000f, 1.0000f,
    0.8000f, 0.9000f,
    0.9000f, 1.0000f,
    0.8000f, 1.0000f,
    0.1000f, 0.1000f,
    0.0500f, 0.1500f,
    0.0500f, 0.0500f,
    0.1000f, 0.1000f,
    0.1500f, 0.1500f,
    0.1500f, 0.0500f,
    0.1000f, 0.1000f,
    0.1500f, 0.0500f,
    0.0500f, 0.1500f,
    0.1000f, 0.1000f,
    0.0500f, 0.0500f,
    0.1500f, 0.1500f,
    0.1000f, 0.1000f,
    0.1000f, 0.2000f,
    0.2000f, 0.2000f,
    0.1000f, 0.1000f,
    0.2000f, 0.2000f,
    0.2000f, 0.1000f,
    0.1000f, 0.1000f,
    0.1000f, 0.2000f,
    0.2000f, 0.2000f,
    0.1000f, 0.1000f,
    0.2000f, 0.2000f,
    0.2000f, 0.1000f,
    0.1000f, 0.1000f,
    0.1000f, 0.2000f,
    0.2000f, 0.2000f,
    0.1000f, 0.1000f,
    0.2000f, 0.2000f,
    0.2000f, 0.1000f,
    0.1000f, 0.1000f,
    0.1000f, 0.2000f,
    0.2000f, 0.2000f,
    0.1000f, 0.1000f,
    0.2000f, 0.2000f,
    0.2000f, 0.1000f,
    0.1000f, 0.1000f,
    0.1000f, 0.2000f,
    0.2000f, 0.2000f,
    0.1000f, 0.1000f,
    0.2000f, 0.2000f,
    0.2000f, 0.1000f,
};

// Aligned vertex coordinates flat array
static const float automag_lvl1_flat_vertices[] = {
    -0.1500f, 0.4000f, 1.4000f,
    -0.1500f, 0.1000f, -0.3000f,
    -0.1500f, 0.1000f, 1.4000f,
    -0.1500f, 0.4000f, 1.4000f,
    -0.1500f, 0.4000f, -1.2000f,
    -0.1500f, 0.1000f, -0.3000f,
    -0.1500f, 0.4000f, -1.2000f,
    -0.1500f, 0.1000f, -1.2000f,
    -0.1500f, 0.1000f, -0.3000f,
    -0.1500f, 0.1000f, -1.2000f,
    -0.1500f, -0.3000f, -0.3000f,
    -0.1500f, 0.1000f, -0.3000f,
    -0.1500f, 0.1000f, -1.2000f,
    -0.1500f, -0.1000f, -1.3000f,
    -0.1500f, -0.3000f, -0.3000f,
    -0.1500f, -0.1000f, -1.3000f,
    -0.1500f, -0.9000f, -1.1000f,
    -0.1500f, -0.3000f, -0.3000f,
    -0.1500f, -0.3000f, -0.3000f,
    -0.1500f, -0.9000f, -1.1000f,
    -0.1500f, -0.9000f, -0.8000f,
    0.1500f, 0.4000f, 1.4000f,
    0.1500f, 0.1000f, 1.4000f,
    0.1500f, 0.1000f, -0.3000f,
    0.1500f, 0.4000f, 1.4000f,
    0.1500f, 0.1000f, -0.3000f,
    0.1500f, 0.4000f, -1.2000f,
    0.1500f, 0.4000f, -1.2000f,
    0.1500f, 0.1000f, -0.3000f,
    0.1500f, 0.1000f, -1.2000f,
    0.1500f, 0.1000f, -1.2000f,
    0.1500f, -0.3000f, -0.3000f,
    0.1500f, 0.1000f, -0.3000f,
    0.1500f, 0.1000f, -1.2000f,
    0.1500f, -0.1000f, -1.3000f,
    0.1500f, -0.3000f, -0.3000f,
    0.1500f, -0.1000f, -1.3000f,
    0.1500f, -0.9000f, -1.1000f,
    0.1500f, -0.3000f, -0.3000f,
    0.1500f, -0.3000f, -0.3000f,
    0.1500f, -0.9000f, -1.1000f,
    0.1500f, -0.9000f, -0.8000f,
    -0.1500f, 0.4000f, -1.2000f,
    -0.1500f, 0.4000f, 1.4000f,
    0.1500f, 0.4000f, 1.4000f,
    -0.1500f, 0.4000f, -1.2000f,
    0.1500f, 0.4000f, 1.4000f,
    0.1500f, 0.4000f, -1.2000f,
    -0.1500f, 0.4000f, 1.4000f,
    -0.1500f, 0.1000f, 1.4000f,
    0.1500f, 0.1000f, 1.4000f,
    -0.1500f, 0.4000f, 1.4000f,
    0.1500f, 0.1000f, 1.4000f,
    0.1500f, 0.4000f, 1.4000f,
    -0.1500f, 0.1000f, 1.4000f,
    -0.1500f, 0.1000f, -0.3000f,
    0.1500f, 0.1000f, -0.3000f,
    0.1500f, 0.1000f, 1.4000f,
    0.1500f, 0.1000f, -0.3000f,
    -0.1500f, 0.1000f, 1.4000f,
    -0.1500f, -0.3000f, -0.3000f,
    0.1500f, -0.3000f, -0.3000f,
    0.1500f, -0.9000f, -0.8000f,
    -0.1500f, -0.3000f, -0.3000f,
    0.1500f, -0.9000f, -0.8000f,
    -0.1500f, -0.9000f, -0.8000f,
    -0.1500f, -0.9000f, -0.8000f,
    -0.1500f, -0.9000f, -1.1000f,
    0.1500f, -0.9000f, -1.1000f,
    -0.1500f, -0.9000f, -0.8000f,
    0.1500f, -0.9000f, -1.1000f,
    0.1500f, -0.9000f, -0.8000f,
    -0.1500f, -0.9000f, -1.1000f,
    0.1500f, -0.9000f, -1.1000f,
    0.1500f, -0.1000f, -1.3000f,
    -0.1500f, -0.9000f, -1.1000f,
    0.1500f, -0.1000f, -1.3000f,
    -0.1500f, -0.1000f, -1.3000f,
    -0.1500f, -0.1000f, -1.3000f,
    0.1500f, -0.1000f, -1.3000f,
    0.1500f, 0.1000f, -1.2000f,
    -0.1500f, -0.1000f, -1.3000f,
    0.1500f, 0.1000f, -1.2000f,
    -0.1500f, 0.1000f, -1.2000f,
    -0.1500f, 0.1000f, -1.2000f,
    0.1500f, 0.1000f, -1.2000f,
    0.1500f, 0.4000f, -1.2000f,
    -0.1500f, 0.1000f, -1.2000f,
    0.1500f, 0.4000f, -1.2000f,
    -0.1500f, 0.4000f, -1.2000f,
    0.0000f, 0.5200f, 1.2000f,
    -0.0500f, 0.4000f, 1.3000f,
    0.0500f, 0.4000f, 1.3000f,
    0.0000f, 0.5200f, 1.2000f,
    0.0500f, 0.4000f, 1.1000f,
    -0.0500f, 0.4000f, 1.1000f,
    0.0000f, 0.5200f, 1.2000f,
    -0.0500f, 0.4000f, 1.1000f,
    -0.0500f, 0.4000f, 1.3000f,
    0.0000f, 0.5200f, 1.2000f,
    0.0500f, 0.4000f, 1.3000f,
    0.0500f, 0.4000f, 1.1000f,
    -0.0600f, 0.4800f, -0.9000f,
    -0.0600f, 0.4800f, -1.1000f,
    0.0600f, 0.4800f, -1.1000f,
    -0.0600f, 0.4800f, -0.9000f,
    0.0600f, 0.4800f, -1.1000f,
    0.0600f, 0.4800f, -0.9000f,
    -0.0600f, 0.4800f, -0.9000f,
    -0.0600f, 0.4000f, -0.9000f,
    0.0600f, 0.4000f, -0.9000f,
    -0.0600f, 0.4800f, -0.9000f,
    0.0600f, 0.4000f, -0.9000f,
    0.0600f, 0.4800f, -0.9000f,
    -0.0600f, 0.4800f, -1.1000f,
    -0.0600f, 0.4000f, -1.1000f,
    0.0600f, 0.4000f, -1.1000f,
    -0.0600f, 0.4800f, -1.1000f,
    0.0600f, 0.4000f, -1.1000f,
    0.0600f, 0.4800f, -1.1000f,
    -0.0600f, 0.4800f, -0.9000f,
    -0.0600f, 0.4000f, -0.9000f,
    -0.0600f, 0.4000f, -1.1000f,
    -0.0600f, 0.4800f, -0.9000f,
    -0.0600f, 0.4000f, -1.1000f,
    -0.0600f, 0.4800f, -1.1000f,
    0.0600f, 0.4800f, -0.9000f,
    0.0600f, 0.4000f, -0.9000f,
    0.0600f, 0.4000f, -1.1000f,
    0.0600f, 0.4800f, -0.9000f,
    0.0600f, 0.4000f, -1.1000f,
    0.0600f, 0.4800f, -1.1000f,
};

// Instantiates and loads the custom mesh directly into GPU memory
static inline Model LoadRetroModel_automag_lvl1(void) {
    Mesh mesh = { 0 };
    mesh.vertexCount = 132;
    mesh.triangleCount = 44;
    
    // Allocate buffer arrays
    mesh.vertices = (float *)malloc(mesh.vertexCount * 3 * sizeof(float));
    mesh.texcoords = (float *)malloc(mesh.vertexCount * 2 * sizeof(float));
    
    // Copy baked coordinates
    for (int i = 0; i < mesh.vertexCount * 3; i++) {
        mesh.vertices[i] = automag_lvl1_flat_vertices[i];
    }
    for (int i = 0; i < mesh.vertexCount * 2; i++) {
        mesh.texcoords[i] = automag_lvl1_texcoords[i];
    }
    
    // Upload structural mesh buffers to Raylib's GPU context
    UploadMesh(&mesh, false);
    
    // Wrap the uploaded mesh inside a Raylib Model
    Model model = LoadModelFromMesh(mesh);
    return model;
}

/* 
========================================================================
BONUS: Authentic PSX Retro Shader for Raylib
========================================================================
Copy this vertex shader code into a "psx.vs" file:

#version 330

// Input vertex attributes
in vec3 vertexPosition;
in vec2 vertexTexCoord;
in vec3 vertexNormal;
in vec4 vertexColor;

// Input uniform values
uniform mat4 mvp;
uniform mat4 matModel;

// Output vertex attributes (passed to fragment shader)
out vec2 fragTexCoord;
out vec4 fragColor;

// Retro effect settings
uniform float jitterAmount = 16.0; // Simulated vertex grid size (higher = more jitter)
uniform vec2 resolution = vec2(320.0, 240.0); // PS1 320x240 render grid

void main()
{
    // Apply standard MVP matrix projection
    vec4 projected = mvp * vec4(vertexPosition, 1.0);
    
    // Vertex Jitter / Wobble: Truncating screen positions simulates PS1 vertex grid rounding!
    vec2 grid = projected.xy / projected.w;
    grid = floor(grid * resolution) / resolution;
    projected.xy = grid * projected.w;
    
    gl_Position = projected;
    
    // Texture Coordinate (No perspective correction emulation)
    fragTexCoord = vertexTexCoord;
    fragColor = vertexColor;
}

------------------------------------------------------------------------
Copy this fragment shader code into a "psx.fs" file:

#version 330

// Input vertex attributes (from vertex shader)
in vec2 fragTexCoord;
in vec4 fragColor;

// Input uniform values
uniform sampler2D texture0;
uniform vec4 colDiffuse;

// Output color
out vec4 finalColor;

void main()
{
    // Sample texture with pixelated filtering (no bilinear interpolators)
    vec4 texelColor = texture(texture0, fragTexCoord);
    
    // Retro lighting: vertex color multiplication for vertex-shaded lighting!
    finalColor = texelColor * colDiffuse * fragColor;
    
    // Simple 16-bit color depth dither or bitwise floor
    finalColor.rgb = floor(finalColor.rgb * 8.0) / 8.0; // Reduce color precision
}

------------------------------------------------------------------------
To use it in your C game loop:

#include "retro_mesh_automag_lvl1.h"

int main() {
    InitWindow(640, 480, "OmegaTech/Raylib PSX Retro Rendering");
    SetTargetFPS(60);
    
    // Load baked low-poly model
    Model retroModel = LoadRetroModel_automag_lvl1();
    
    // Load retro texture and assign to model
    Image img = LoadImage("texture.png"); // generated texture
    Texture2D tex = LoadTextureFromImage(img);
    UnloadImage(img);
    retroModel.materials[0].maps[MATERIAL_MAP_DIFFUSE].texture = tex;
    
    // Load PSX Retro Shader
    Shader psxShader = LoadShader("psx.vs", "psx.fs");
    retroModel.materials[0].shader = psxShader;
    
    // Initialize Camera
    Camera camera = { { 0.0f, 2.0f, 4.0f }, { 0.0f, 0.0f, 0.0f }, { 0.0f, 1.0f, 0.0f }, 45.0f, CAMERA_PERSPECTIVE };
    
    while (!WindowShouldClose()) {
        UpdateCamera(&camera, CAMERA_ORBITAL);
        
        BeginDrawing();
            ClearBackground(DARKGRAY);
            BeginMode3D(camera);
                // Render the low poly mesh!
                DrawModel(retroModel, (Vector3){ 0.0f, 0.0f, 0.0f }, 1.0f, WHITE);
            EndMode3D();
            DrawFPS(10, 10);
        EndDrawing();
    }
    
    UnloadModel(retroModel);
    UnloadShader(psxShader);
    UnloadTexture(tex);
    CloseWindow();
    return 0;
}
========================================================================
*/

#endif // RETRO_MESH_AUTOMAG_LVL1_H
